services:
  lavalink:
    build: .
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    environment:
      - _JAVA_OPTIONS=-Xmx2G
